const dotenv = require('dotenv');
dotenv.config();
const { PORT } = process.env;
const {
  HOST, USER, PASSWORD, DB, DB_PORT,
  FRONTEND_URL, SECRET_JWT_KEY,
  AWS_ACCESS_KEY_ID,S3_FORCE_PATH_STYLE , AWS_SECRET_ACCESS_KEY, AWS_ENDPOINT_URL_S3, AWS_REGION
} = process.env;

module.exports = {
  PORT,
  HOST,
  USER,
  PASSWORD,
  DB,
  DB_PORT,
  FRONTEND_URL,
  SECRET_JWT_KEY,
  S3_REGION: AWS_REGION,
  S3_ENDPOINT: AWS_ENDPOINT_URL_S3,
  S3_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID,
  S3_SECRET_ACCESS_KEY: S3_SECRET_ACCESS_KEY || AWS_SECRET_ACCESS_KEY,
  S3_FORCE_PATH_STYLE: S3_FORCE_PATH_STYLE 
};
