const dotenv = require('dotenv');
dotenv.config();
const { PORT } = process.env;
const {
  HOST, USER, PASSWORD, DB, DB_PORT,
  FRONTEND_URL, SECRET_JWT_KEY,
  S3_BUCKET, S3_REGION, S3_ENDPOINT,
  S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY,
  S3_FORCE_PATH_STYLE, S3_PUBLIC_BASE_URL,
} = process.env;

module.exports = {
  PORT,
  HOST,
  USER,
  PASSWORD,
  DB,
  DB_PORT,
  FRONTEND_URL,
  SECRET_JWT_KEY,
  S3_BUCKET,
  S3_REGION: S3_REGION || 'us-east-1',
  S3_ENDPOINT,
  S3_ACCESS_KEY_ID,
  S3_SECRET_ACCESS_KEY,
  S3_FORCE_PATH_STYLE: S3_FORCE_PATH_STYLE === 'true',
  S3_PUBLIC_BASE_URL,
};
